version: 2.1

jobs:
  build:
    docker:
      - image: circleci/openjdk:17
    steps:
      - checkout
      - run: mvn -B clean install

  deploy:
    docker:
      - image: circleci/python:3.9
    steps:
      - checkout
      - run:
          name: Install Heroku CLI
          command: |
            curl https://cli-assets.heroku.com/install.sh | sh

      - run:
          name: Deploy to Heroku
          command: |
            git remote add heroku https://git.heroku.com/$HEROKU_APP_NAME.git
            git push heroku master

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
