# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      # nazwy zmiennych sa nieprzypadkowe, wynikaja z uploadem na heroku
      - image: cimg/openjdk:17.0
        environment:
          JDBC_DATABASE_URL: jdbc:postgresql://localhost:5432/circle_db
          JDBC_DATABASE_USERNAME: root
          JDBC_DATABASE_PASSWORD: root

      - image: cimg/postgres:15.0
        environment:
          POSTGRES_DB: circle_db
          POSTGRES_USER: root
          POSTGRES_PASSWORD: root



    # Specify service dependencies here if necessary
    # CircleCI maintains a library of pre-built images
    # documented at https://circleci.com/docs/2.0/circleci-images/
    # - image: circleci/postgres:9.4

    working_directory: ~/circleci-spring-example

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn dependency:go-offline

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}

      # run tests!
      - run: mvn test
